import PDFDocument from 'pdfkit';

export function generateReportPdf(report, res) {
  const { audit, summary, by_domain, non_conformities } = report;
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="audit-${audit.id}-report.pdf"`);
  doc.pipe(res);

  const blue   = '#2563eb';
  const dark   = '#0f172a';
  const gray   = '#64748b';
  const red    = '#dc2626';
  const green  = '#059669';
  const yellow = '#d97706';
  const W = 495;

  // ── Header ──
  doc.rect(0, 0, 595, 90).fill(blue);
  doc.fill('#fff').fontSize(22).font('Helvetica-Bold').text('PAAI', 50, 28);
  doc.fontSize(11).font('Helvetica').text('ISO 27001 Audit Report', 50, 55);
  doc.fontSize(9).text(`${audit.company_name}  ·  ${audit.company_email}`, 50, 70);
  doc.moveDown(0);

  // ── Audit Info ──
  doc.y = 110;
  doc.fill(dark).fontSize(16).font('Helvetica-Bold').text(audit.title, 50, 110);
  doc.fontSize(9).font('Helvetica').fill(gray)
    .text(`Started: ${new Date(audit.start_date).toLocaleDateString('en-GB')}   |   Status: ${audit.status}`, 50, 132);

  // ── Summary boxes ──
  const stats = [
    { label: 'Total Controls', value: summary.total, color: dark },
    { label: 'Answered',       value: summary.answered, color: blue },
    { label: 'Compliant',      value: summary.compliant, color: green },
    { label: 'Non-Conformities', value: summary.non_conformities, color: red },
    { label: 'Compliance Rate', value: `${summary.compliance_pct}%`, color: summary.compliance_pct >= 70 ? green : red },
  ];

  const boxW = 88;
  let bx = 50;
  const by = 155;
  for (const s of stats) {
    doc.roundedRect(bx, by, boxW, 52, 4).fill('#f8fafc').stroke('#e2e8f0');
    doc.fill(s.color).fontSize(18).font('Helvetica-Bold').text(String(s.value), bx, by + 8, { width: boxW, align: 'center' });
    doc.fill(gray).fontSize(7.5).font('Helvetica').text(s.label, bx, by + 34, { width: boxW, align: 'center' });
    bx += boxW + 8;
  }

  doc.y = 225;

  // ── Compliance bar ──
  doc.moveDown(0.5);
  doc.fill(dark).fontSize(11).font('Helvetica-Bold').text('Compliance Overview', 50);
  doc.moveDown(0.3);
  doc.rect(50, doc.y, W, 12).fill('#e2e8f0');
  const fillW = Math.round((summary.compliance_pct / 100) * W);
  doc.rect(50, doc.y - 12, fillW, 12).fill(summary.compliance_pct >= 70 ? green : red);
  doc.fill(gray).fontSize(8).font('Helvetica')
    .text(`${summary.compliance_pct}% compliant  (${summary.compliant}/${summary.answered} answered controls)`, 50, doc.y + 2);
  doc.moveDown(1.2);

  // ── By Domain ──
  doc.fill(dark).fontSize(11).font('Helvetica-Bold').text('Results by Domain');
  doc.moveDown(0.4);

  const domainOrder = ['Organizacional', 'Pessoas', 'Físico', 'Tecnológico'];
  for (const domain of domainOrder) {
    const d = by_domain[domain];
    if (!d) continue;
    const pct = d.total > 0 ? Math.round((d.compliant / d.total) * 100) : 0;
    const color = pct >= 70 ? green : pct >= 40 ? yellow : red;

    doc.fill(dark).fontSize(9.5).font('Helvetica-Bold').text(`${domain}`, 50, doc.y, { continued: true });
    doc.fill(color).font('Helvetica').text(`  ${pct}%  (${d.compliant}/${d.total})`, { align: 'right' });

    const barY = doc.y + 2;
    doc.rect(50, barY, W, 7).fill('#e2e8f0');
    doc.rect(50, barY, Math.round((pct / 100) * W), 7).fill(color);
    doc.moveDown(0.9);
  }

  doc.moveDown(0.5);

  // ── Non-Conformities ──
  if (non_conformities.length > 0) {
    if (doc.y > 650) doc.addPage();
    doc.fill(dark).fontSize(11).font('Helvetica-Bold').text('Non-Conformities & Recommendations');
    doc.moveDown(0.4);

    for (const nc of non_conformities) {
      if (doc.y > 700) doc.addPage();

      doc.roundedRect(50, doc.y, W, 8).fill('#fee2e2');
      doc.fill(red).fontSize(9).font('Helvetica-Bold')
        .text(`${nc.codigo} — ${nc.titulo}`, 55, doc.y + 10);
      doc.moveDown(0.3);

      if (nc.observation) {
        doc.fill(gray).fontSize(8.5).font('Helvetica')
          .text(`Observation: ${nc.observation}`, 55, doc.y, { width: W - 10 });
        doc.moveDown(0.3);
      }

      doc.fill(yellow).fontSize(8.5).font('Helvetica-Bold').text('Recommendation:', 55, doc.y);
      doc.fill('#78350f').font('Helvetica').fontSize(8.5)
        .text(nc.recomendacao, 55, doc.y + 11, { width: W - 10 });
      doc.moveDown(1.2);
    }
  } else {
    doc.fill(green).fontSize(10).font('Helvetica-Bold')
      .text('✓ No non-conformities identified. Full compliance achieved.', 50);
  }

  // ── Footer ──
  const pages = doc.bufferedPageRange ? doc.bufferedPageRange() : { count: 1 };
  doc.fontSize(7.5).fill(gray).font('Helvetica')
    .text(
      `Generated by PAAI · ${new Date().toLocaleDateString('en-GB')}`,
      50, 800, { align: 'center', width: W }
    );

  doc.end();
}
